redirectsOrigin = "config"
plugins = []
headers = []

[build]
edge_functions = "/Users/axelskotnicki/Downloads/Autre SaaS/avatarads-membres/mcp-proxy/netlify/edge-functions"
publish = "/Users/axelskotnicki/Downloads/Autre SaaS/avatarads-membres/mcp-proxy"
publishOrigin = "default"
base = "/Users/axelskotnicki/Downloads/Autre SaaS/avatarads-membres/mcp-proxy"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/.well-known/*"
to = "https://guvwgiejzkiodghywpwj.supabase.co/functions/v1/mcp/.well-known/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "https://guvwgiejzkiodghywpwj.supabase.co/functions/v1/mcp/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]