# Séquences e-mail AvatarAds (05/10/2026) — source des textes, avant intégration dans supabase/functions/email-drip.
# Ton mixte (voix d'Axel dans une mise en page légère), aucun émoji dans les objets, une idée par e-mail.
# {prenom} = prénom (repli « Salut, »), {plan}. Aucun e-mail sur les crédits restants ni le renouvellement : uniquement du conseil (Axel 05/10).
# Structure de chaque e-mail, comme une vidéo (Axel 05/10) : ACCROCHE (titre + 1re phrase) → CONTENU (l'image, à l'endroit
# du marqueur VISUEL, et le texte qui la décrit exactement) → CTA (une phrase qui pousse à l'action, puis le bouton).
APP = 'https://avatarads.fr/app/'
VISUEL = '[visuel]'

PROSPECTS = [
  dict(id='p0', quand='À l’inscription (remplace « welcome_free »)', objet='Ta première vidéo en 5 minutes',
       preheader='Une photo suffit pour commencer.',
       titre='Une photo suffit pour ta première vidéo',
       corps=[
         'C’est Axel, le créateur d’AvatarAds. Merci d’avoir créé ton compte.',
         'Le plus simple pour commencer : prends une photo (toi, un avatar ou ton produit), ouvre Express et écris ce que la personne doit dire. Une minute plus tard, elle te parle face caméra :',
         VISUEL,
         'Tu as déjà un audio ou un rush ? Montage IA le monte avec sous-titres, animations et musique. Tu utilises Claude ? Branche AvatarAds dedans et demande ta vidéo en une phrase.',
         '<b>Fais ta première vidéo maintenant.</b> Si tu bloques, réponds à ce mail : je lis tout.',
       ],
       cta='Faire ma première vidéo', url=APP + '#express'),
  dict(id='p1', quand='H+2 (2 heures après l’inscription)', objet='Ta voiture devient un tank',
       preheader='Omni transforme n’importe quel objet de ta vidéo.',
       titre='Transforme n’importe quel objet de ta vidéo',
       corps=[
         'Omni, c’est l’outil qui surprend le plus quand on le découvre. Tu filmes n’importe quoi avec ton téléphone, tu écris ce que ça doit devenir, et Omni le transforme dans la vidéo.',
         'Ici, une simple Clio garée dans la rue :',
         VISUEL,
         'La caméra bouge exactement pareil et la rue ne change pas : seul l’objet est transformé.',
         '<b>Filme un objet autour de toi</b> et écris ce qu’il doit devenir.',
       ],
       cta='Essayer Omni', url=APP + '#omni'),
  dict(id='p2', quand='J+1', objet='Tu peux demander tes pubs à Claude',
       preheader='AvatarAds se branche dans Claude en deux minutes.',
       titre='Ta prochaine pub, en une phrase',
       corps=[
         'Si tu utilises déjà Claude, il existe un raccourci : AvatarAds s’y branche comme un connecteur, en deux minutes.',
         'Tu ajoutes la photo de ton produit, tu écris « crée 4 influenceurs UGC qui présentent ce produit », et le résultat arrive directement dans la conversation :',
         VISUEL,
         'Ça marche aussi pour les vidéos, le montage et les visuels publicitaires : tout part de la même discussion.',
         '<b>Branche AvatarAds dans Claude</b> et essaie avec ton propre produit.',
       ],
       cta='Connecter Claude', url='https://avatarads.fr/claude.html'),
  dict(id='p3', quand='J+3', objet='Une photo, une vidéo qui parle',
       preheader='Le format qui marche le mieux sur TikTok et Reels.',
       titre='Le format UGC, sans te filmer',
       corps=[
         'Le format qui marche le mieux en ce moment sur TikTok et Reels : quelqu’un qui présente un produit face caméra, comme un vrai client.',
         'Avec Express, tu pars d’une photo de ton produit et tu écris ce que la personne doit dire. La voix, les gestes et le décor sont générés pour toi :',
         VISUEL,
         '<b>À tester aujourd’hui :</b> prends la photo de ton produit et écris « une jeune femme dans sa salle de bain présente ce produit en huit secondes ».',
       ],
       cta='Essayer Express', url=APP + '#express'),
  dict(id='p4', quand='J+5', objet='Ton audio, monté en quelques minutes',
       preheader='Sous-titres, animations et musique, sans timeline.',
       titre='Le montage, sans y passer la soirée',
       corps=[
         'Le montage, c’est souvent ce qui prend le plus de temps. Montage IA s’en charge à ta place.',
         'Tu déposes ton audio ou ta vidéo : il coupe, ajoute les sous-titres, les animations qui illustrent ce que tu dis et la musique. Voilà trois moments d’une vidéo montée comme ça :',
         VISUEL,
         'Tu récupères une vidéo prête à poster, que tu peux encore retoucher dans l’Éditeur.',
         '<b>Dépose ton prochain audio</b> et regarde ce qu’il en fait.',
       ],
       cta='Monter une vidéo', url=APP + '#montage'),
  dict(id='p5', quand='J+7', objet='Reproduis une tendance avec une seule photo',
       preheader='Sans te filmer, sans danser.',
       titre='Surfer sur une tendance sans te filmer',
       corps=[
         'Une danse, un geste, une trend qui tourne : Motion Control fait reproduire exactement ces mouvements à n’importe quel personnage, à partir d’une seule photo.',
         VISUEL,
         'C’est le moyen le plus rapide de reprendre une tendance du moment avec ton avatar ou ta mascotte.',
         '<b>Choisis une trend qui tourne en ce moment</b> et essaie avec ta photo.',
       ],
       cta='Essayer Motion Control', url=APP + '#motion'),
  dict(id='p6', quand='J+10', objet='Une campagne complète en une matinée',
       preheader='Visuels, vidéos UGC et déclinaisons, au même endroit.',
       titre='Ta prochaine campagne en une matinée',
       corps=[
         'Soldes, fêtes, lancement : les temps forts arrivent vite. Avec la photo de ton produit, tu peux préparer toute ta campagne en une matinée.',
         'On commence par les visuels : Images IA décline ton produit sous plusieurs angles, prêts à poster.',
         VISUEL,
         'Ensuite, trois vidéos UGC avec Express (le prix, le résultat, l’avis) et une vidéo explicative avec Montage IA.',
         '<b>Choisis ton prochain temps fort</b> et commence par les visuels.',
       ],
       cta='Préparer ma campagne', url=APP + '#images'),
  dict(id='p7', quand='J+14', objet='« Je ne saurai pas m’en servir »',
       preheader='C’est la phrase que j’entends le plus.',
       titre='Trois gestes, c’est tout',
       corps=[
         '« Je ne saurai pas m’en servir. » C’est la phrase que j’entends le plus souvent. Pourtant, chaque outil marche pareil : tu déposes, tu choisis, tu génères.',
         'Exemple avec Motion Control : tu déposes la vidéo dont tu veux copier les gestes, tu déposes la photo de ton personnage, puis tu cliques sur « Générer le mouvement ».',
         VISUEL,
         'Pas d’idée de vidéo ? Réponds-moi avec ce que tu vends ou ce que tu racontes, je te propose trois idées adaptées.',
         '<b>Tout ça pour le prix d’un café par jour</b>, sans engagement.',
       ],
       cta='Voir les offres', url='https://avatarads.fr/tarifs.html'),
]

# Ensuite : une idée toutes les deux semaines jusqu'à l'abonnement (rotation), + une idée de saison selon le mois.
LONGUE = [
  dict(id='l1', quand='J+28, puis rotation toutes les 2 semaines', objet='La vidéo qui arrête le scroll',
       preheader='Un objet du quotidien qui se transforme sous tes yeux.',
       titre='Le genre de vidéo qu’on regarde deux fois',
       corps=[
         'Sur TikTok, tu as une seconde pour qu’on s’arrête sur ta vidéo. Rien ne marche mieux qu’un objet du quotidien qui se transforme sous nos yeux.',
         'Avec Omni, tu filmes ta voiture, tu écris ce qu’elle doit devenir, et la vidéo est transformée :',
         VISUEL,
         'Ta voiture, ton bureau, ton produit : tout peut devenir autre chose, avec exactement le même mouvement de caméra.',
         '<b>Choisis l’objet de ta prochaine vidéo</b> et laisse Omni le transformer.',
       ],
       cta='Essayer Omni', url=APP + '#omni'),
  dict(id='l2', quand='rotation', objet='Ton avatar parle avec ta voix',
       preheader='Sans caméra, sans micro de studio.',
       titre='Fais parler un avatar avec ta voix',
       corps=[
         'Tu veux publier sans te filmer ? Choisis un avatar, enregistre ta voix au téléphone (ou écris ton texte) : le Générateur le fait parler avec tes mots, sous-titres et musique compris.',
         VISUEL,
         'Parfait pour une chaîne sans visage, ou pour publier tous les jours sans tourner.',
         '<b>Enregistre quinze secondes</b> et regarde ton avatar parler.',
       ],
       cta='Ouvrir le Générateur', url=APP + '#generateur'),
  dict(id='l3', quand='rotation', objet='Un son propre, même enregistré au téléphone',
       preheader='Le détail qui fait passer pour un pro.',
       titre='Le son, c’est la moitié de la vidéo',
       corps=[
         'Un souffle, une pièce qui résonne, un bruit de rue : on décroche d’une vidéo en deux secondes quand le son est mauvais.',
         'Le nettoyage audio réduit le bruit, garde un volume constant et coupe les silences, en un clic :',
         VISUEL,
         'Même enregistré au téléphone, ta voix sonne propre du début à la fin.',
         '<b>Dépose ton dernier enregistrement</b> et écoute la différence.',
       ],
       cta='Nettoyer mon audio', url=APP + '#audio'),
  dict(id='l4', quand='selon le mois (ex. novembre)', objet='Black Friday : tes visuels prêts en une matinée',
       preheader='Une idée de saison, prête à adapter.', titre='L’idée du mois : le Black Friday',
       corps=[
         'Le Black Friday arrive. Trois visuels à préparer dès maintenant : les raisons d’acheter, un avant / après, et l’annonce de ton offre.',
         VISUEL,
         'Avec Images IA, chacun se fait en quelques secondes à partir de la photo de ton produit.',
         '<b>Prépare tes visuels maintenant</b>, pas la veille.',
       ],
       cta='Créer mes visuels', url=APP + '#images'),
]

CLIENTS = [
  dict(id='c0', quand='À l’abonnement (remplace « welcome »)', objet='Bienvenue, voilà par où commencer',
       preheader='Mon conseil pour ta première heure.', titre='Ton abonnement {plan} est actif',
       corps=[
         'Merci pour ta confiance, ton studio est prêt. Mon conseil pour ta première heure : commence par une photo.',
         VISUEL,
         'Ouvre Express, ajoute une photo (toi, un avatar ou ton produit) et écris ce que la personne doit dire. Ensuite, essaie Montage IA avec un audio. Et si tu utilises Claude, branche AvatarAds dedans pour tout demander en une phrase.',
         '<b>Si tu bloques, réponds à ce mail</b> : je t’aide directement.',
       ],
       cta='Faire ma première vidéo', url=APP + '#express'),
  dict(id='c1', quand='J+2, s’il n’a encore rien créé', objet='Ta première vidéo t’attend',
       preheader='La plus simple à faire : une photo avec ton produit.', titre='Ta première vidéo, avec ton produit',
       corps=[
         'Tu n’as pas encore créé de vidéo ? Voilà la plus simple pour commencer : une photo de quelqu’un qui tient ton produit.',
         'Ajoute-la dans Express et écris ce que la personne doit dire, par exemple « présente ce produit comme si tu le recommandais à un ami ». Voilà ce que ça donne avec différents produits :',
         VISUEL,
         'Pas de photo sous la main ? Prends-toi en selfie avec ton produit, ou crée-la avec Images IA.',
         '<b>Ouvre Express avec la photo de ton produit</b>, ta vidéo arrive en quelques minutes.',
       ],
       cta='Créer ma première vidéo', url=APP + '#express'),
  dict(id='c2', quand='Après 7 jours sans création', objet='Une vidéo pour cette semaine ?',
       preheader='Une idée qui prend cinq minutes.', titre='Une idée pour cette semaine',
       corps=[
         'Ça fait une semaine qu’on ne t’a pas vu dans le studio. Voilà une idée qui prend cinq minutes.',
         'Enregistre au téléphone un conseil de ton métier, trente secondes suffisent. Dépose l’audio dans Montage IA : il en fait une vidéo, avec un avatar qui parle, les sous-titres, les images qui illustrent ce que tu dis et la musique.',
         VISUEL,
         '<b>Enregistre ton conseil</b> et laisse Montage IA faire le reste.',
       ],
       cta='Monter mon conseil', url=APP + '#montage'),
]

# L'idée de la semaine : une fonctionnalité par semaine, chaque e-mail annonce la suivante, puis la boucle recommence.
ROTATION = [
  dict(id='w1', quand='Semaine 1 de la rotation', objet='Cette semaine : reprends une trend avec ton avatar',
       preheader='L’idée de la semaine : Motion Control.', titre='L’idée de la semaine : Motion Control',
       corps=[
         'Cette semaine, reprends une tendance TikTok avec ton avatar : choisis une vidéo de danse ou de geste qui tourne en ce moment, ajoute la photo de ton personnage, et Motion Control reproduit chaque mouvement.',
         VISUEL,
         'La semaine prochaine : Omni, pour transformer n’importe quel objet de ta vidéo en ce que tu veux.',
         '<b>Choisis une trend</b> et lance-toi.',
       ],
       cta='Essayer Motion Control', url=APP + '#motion'),
  dict(id='w2', quand='Semaine 2', objet='Cette semaine : ta voiture devient une Bugatti',
       preheader='L’idée de la semaine : Omni.', titre='L’idée de la semaine : Omni',
       corps=[
         'Cette semaine, filme ta voiture (ou n’importe quel objet) et demande à Omni d’en faire autre chose. Ici, une Clio garée dans la rue devient une Bugatti :',
         VISUEL,
         'Le mouvement de la caméra reste identique, seul ce que tu demandes change. Le genre de vidéo qu’on regarde deux fois.',
         'La semaine prochaine : Express, pour faire présenter ton produit par des créateurs UGC.',
         '<b>Filme quelque chose autour de toi</b> et transforme-le.',
       ],
       cta='Essayer Omni', url=APP + '#omni'),
  dict(id='w3', quand='Semaine 3', objet='Cette semaine : ton produit présenté par trois créateurs',
       preheader='L’idée de la semaine : Express.', titre='L’idée de la semaine : Express',
       corps=[
         'Cette semaine, fais présenter ton produit par plusieurs créateurs UGC. Une photo par créateur avec ton produit, une phrase pour dire ce qu’il doit raconter, et Express génère chaque vidéo.',
         VISUEL,
         'Change d’angle à chaque vidéo : le prix, le résultat, l’avis. Tu verras vite laquelle marche le mieux.',
         'La semaine prochaine : Montage IA, pour monter une vidéo sans ouvrir de timeline.',
         '<b>Prends la photo de ton produit</b> et lance ta première série.',
       ],
       cta='Essayer Express', url=APP + '#express'),
  dict(id='w4', quand='Semaine 4', objet='Cette semaine : donne du rythme à ta vidéo',
       preheader='L’idée de la semaine : Montage IA.', titre='L’idée de la semaine : Montage IA',
       corps=[
         'Cette semaine, transforme une vidéo face caméra toute simple en vidéo qui retient l’attention. Dépose ta vidéo brute (ou juste l’audio) dans Montage IA :',
         VISUEL,
         'Il ajoute des animations qui illustrent ce que tu dis (en split screen ou en plein écran), les sous-titres, les mots forts et la musique. Tu n’ouvres jamais de timeline.',
         'La semaine prochaine : Images IA, pour créer tes créateurs UGC en une phrase.',
         '<b>Dépose ta prochaine vidéo</b> et regarde la différence.',
       ],
       cta='Monter une vidéo', url=APP + '#montage'),
  dict(id='w5', quand='Semaine 5, puis retour à la semaine 1', objet='Cette semaine : tes créateurs UGC en une phrase',
       preheader='L’idée de la semaine : Images IA.', titre='L’idée de la semaine : Images IA',
       corps=[
         'Cette semaine, crée tes propres créateurs UGC. Décris la personne en une phrase, Images IA génère des photos ultra réalistes, prêtes à poster ou à faire parler avec Express.',
         VISUEL,
         'Ici, la phrase était « créatrice UGC, selfie lifestyle, lumière naturelle, streetwear décontracté ».',
         'La semaine prochaine : Motion Control, pour reprendre une trend avec ton avatar.',
         '<b>Écris ta première description</b> et regarde le résultat.',
       ],
       cta='Créer une image', url=APP + '#images'),
]

# Abonnés arrivés à 0 crédit : une relance par mois au plus (jamais pendant une annulation en cours)
ZERO = [
  dict(id='z0', quand='Abonné à 0 crédit (une fois par mois au plus)', objet='Tu as utilisé tous tes crédits du mois',
       preheader='Plutôt bon signe : ça veut dire que tu publies.', titre='Tu as tout utilisé ce mois-ci',
       corps=[
         'Tes crédits du mois sont épuisés. C’est plutôt bon signe : ça veut dire que tu produis, et c’est la régularité qui fait les vues.',
         'Deux vidéos UGC et un visuel produit, chacun pour un produit différent : c’est ce genre de contenu, publié chaque semaine, qui fait tourner un compte :',
         VISUEL,
         'Pour ne pas casser ton rythme, deux options :',
         ('liste', [
           '<b>un pack de crédits</b>, en un clic, sans changer d’abonnement ;',
           '<b>le plan au-dessus</b>, si tu arrives à zéro chaque mois.',
         ]),
         '<b>Recharge maintenant</b> et reprends là où tu t’es arrêté.',
       ],
       cta='Recharger mes crédits', url=APP + '#recharge'),
]

# Visuel de chaque e-mail : fichier dans images/ (fabriqué par images.py), texte alternatif, légende (décrit exactement l'image).
VISUELS = {
  'p0': ('photo-video-lune.jpg', 'Une photo d’une créatrice avec une lampe, puis la vidéo Express où elle parle',
         'À gauche la photo de départ, à droite la vidéo Express où elle parle.'),
  'p2': ('claude-influenceurs.jpg', 'Quatre créateurs UGC qui présentent la même canette',
         'Demandé à Claude : « crée 4 influenceurs UGC qui présentent ce produit ».'),
  'p1': ('omni-tank.jpg', 'Une Clio garée dans la rue, puis la même vidéo où elle est devenue un tank',
         'La même vidéo, avant et après Omni : la Clio est devenue un tank.'),
  'p3': ('ugc-produits.jpg', 'Trois créateurs UGC qui présentent un produit face caméra',
         'Trois vidéos UGC générées avec AvatarAds, chacune présente un produit face caméra.'),
  'p4': ('montage-moments.jpg', 'Trois moments d’une vidéo montée par Montage IA',
         'Trois moments d’une vidéo montée par Montage IA : sous-titres, animation, visuels.'),
  'p5': ('motion-control-geste.jpg', 'Deux personnages qui font exactement le même geste',
         'Le même geste, reproduit par deux personnages à partir d’une seule vidéo.'),
  'p6': ('campagne-visuels.jpg', 'Trois visuels publicitaires pour une boisson',
         'Trois visuels d’une même campagne, trois angles différents, générés avec Images IA.'),
  'p7': ('trois-gestes.jpg', 'Motion Control : une vidéo, une photo, un bouton Générer le mouvement',
         'La vidéo à gauche, la photo à droite, un clic sur « Générer le mouvement ».'),
  'l1': ('omni-helicoptere.jpg', 'Une voiture transformée en hélicoptère dans la même vidéo',
         'La même vidéo, avant et après Omni : la voiture est devenue un hélicoptère.'),
  'l2': ('generateur-voix.jpg', 'Un avatar et un enregistrement de voix dans le Générateur',
         'Un avatar, ta voix enregistrée au micro : le Générateur le fait parler.'),
  'l3': ('audio-avant-apres.jpg', 'Forme d’onde avant et après le nettoyage audio',
         'Le même enregistrement, avant et après le nettoyage.'),
  'l4': ('saison-offre.jpg', 'Trois visuels : les raisons d’acheter, un avant / après, une offre limitée',
         'Les raisons d’acheter, un avant / après, l’annonce de l’offre : trois visuels générés avec Images IA.'),
  'c0': ('photo-video-villa.jpg', 'Une photo, puis la vidéo où la personne parle',
         'Une photo transformée en vidéo qui parle : le premier essai que je te conseille.'),
  'c1': ('ugc-premiere-video.jpg', 'Quatre créateurs UGC qui présentent chacun un produit face caméra',
         'Quatre vidéos UGC générées avec AvatarAds, chacune avec son produit.'),
  'c2': ('montage-audio-video.jpg', 'Un audio, puis la vidéo montée par Montage IA avec un avatar et une image en incrustation',
         'Un audio en entrée, une vidéo montée en sortie : avatar, sous-titres et image d’illustration.'),
  'w1': ('motion-control-reference.jpg', 'La vidéo de référence et le personnage qui reproduit ses gestes',
         'La vidéo de référence et le personnage qui reproduit ses gestes, image par image.'),
  'w2': ('omni-bugatti.jpg', 'Une Clio garée dans la rue, puis la même vidéo où elle est devenue une Bugatti',
         'La même vidéo, avant et après Omni : la Clio est devenue une Bugatti.'),
  'w3': ('ugc-createurs.jpg', 'Trois créateurs UGC qui présentent chacun un produit face caméra',
         'Trois vidéos UGC générées avec AvatarAds, un créateur et un produit par vidéo.'),
  'w4': ('montage-brute-split.jpg', 'Une vidéo face caméra brute, puis la même après Montage IA en split screen avec une animation',
         'À gauche la vidéo brute, à droite après Montage IA : une animation qui illustre ce qu’il dit, en split screen.'),
  'w5': ('imagesia-createurs.jpg', 'Trois créatrices UGC générées avec Images IA',
         'Trois créatrices générées avec Images IA à partir d’une seule phrase.'),
  'z0': ('credits-trio.jpg', 'Un créateur avec un parfum, une créatrice avec un sérum et un visuel publicitaire pour une canette',
         'Un parfum, un sérum, une canette : deux vidéos UGC et un visuel produit, générés avec AvatarAds.'),
}
